### ISSUE TITLE
Issue in analyze_scalar_field.py

### ISSUE THREAD

**Issue by david-zwicker** [zwicker-group/py-pde#121]
### Discussed in https://github.com/zwicker-group/py-pde/discussions/120

<div type='discussions-op-text'>

<sup>Originally posted by **GenB31415** August 14, 2021</sup>
Dear authors, 
while execution of the example 'analyze_scalar_field.py' I met that from 4 subplots only [0,0] shows the expected information, but other 3 are empty. The following traceback info emerges
[for short: path ---> ...\AppData\Local\Programs\Python\Python39\lib\site-packages]]

Traceback (most recent call last):
  File "...\analyze_scalar_field.py", line 26, in <module>
    smoothed.plot(ax=axes[1, 0], title="Smoothed field")
  File "path\pde\tools\plotting.py", line 287, in wrapper  
    reference = wrapped(*args, ax=ax, **kwargs)
  File "path\pde\fields\base.py", line 1907, in plot       
    reference = self._plot_image(**kwargs)
  File "path\pde\fields\base.py", line 1727, in _plot_image
    add_scaled_colorbar(axes_image, ax=ax)
  File "path\pde\tools\plotting.py", line 95, in add_scaled_colorbar
    cax = divider.append_axes("right", size=width, pad=pad)
  File "path\mpl_toolkits\axes_grid1\axes_divider.py", line 551, in append_axes
    self._fig.add_axes(ax)
  File "path\matplotlib\figure.py", line 653, in add_axes
    return self._add_axes_internal(a, key)
  File "path\matplotlib\figure.py", line 789, in _add_axes_internal
    self.sca(ax)
  File "path\matplotlib\figure.py", line 1496, in sca
    self._axobservers.process("_axes_change_event", self)
  File "path\matplotlib\cbook\__init__.py", line 275, in process
    self.exception_handler(exc)
  File "path\matplotlib\cbook\__init__.py", line 89, in _exception_printer
    raise exc
  File "path\matplotlib\cbook\__init__.py", line 270, in process
    func(*args, **kwargs)
  File "path\matplotlib\figure.py", line 2861, in <lambda>
    self._axobservers.connect("_axes_change_event", lambda arg: func(arg))
  File "path\matplotlib\backend_bases.py", line 2765, in notify_axes_change
    self.toolbar.update()
  File "path\matplotlib\backend_bases.py", line 3330, in update
    self.set_history_buttons()
  File "path\matplotlib\backends\_backend_tk.py", line 666, in set_history_buttons
    self._buttons['Back']['state'] = state_map[can_back]
  File "...\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1657, in __setitem__
    self.configure({key: value})
  File "...\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1646, in configure
    return self._configure('configure', cnf, kw)
  File "...\AppData\Local\Programs\Python\Python39\lib\tkinter\__init__.py", line 1636, in _configure
    self.tk.call(_flatten((self._w, cmd)) + self._options(cnf))
_tkinter.TclError: invalid command name ".!navigationtoolbar2tk.!button2"

How to overcome this issue ? Thank you in advance.</div>

**Comment by david-zwicker** [comment]
This problem should be resolved with the latest version of the package. Please reopen if problems persist.
